-- Development seed data. Run after schema.sql:
--   psql "$DATABASE_URL" -f db/seed.sql

insert into departments (name, code) values
    ('Computer Science & Engg.', 'CSE'),
    ('Electronics & Communication Engg.', 'ECE'),
    -- Deliberately has no students: makes INNER vs LEFT JOIN return different rows.
    ('Mechanical Engg.', 'ME');

-- Identity ids are generated by Postgres, so look departments up by their natural key (code)
-- instead of hard-coding ids.
insert into students (name, email, department_id) values
    ('Kunal', 'kunal@example.com', (select id from departments where code = 'CSE')),
    ('Asha',  'asha@example.com',  (select id from departments where code = 'CSE')),
    ('Ravi',  'ravi@example.com',  (select id from departments where code = 'ECE'));
